server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  error:
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never


spring:
  # application
  application:
    name: devtools
  # database
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:devtool}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    hikari:
      auto-commit: false
      maximum-pool-size: ${DATASOURCE_MAX_POOL_SIZE:10}
    dbcp2:
      validation-query: SELECT 1
  # jpa
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.${DATABASE_PLATFORM:H2Dialect}

  messages:
    encoding: UTF-8
    basename: classpath:messages
    extension:
      error-message:
        code-prefix: error.
        title-suffix: .title
        message-suffix: .message
    fallback-to-system-locale: true

  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin}
      roles: ADMIN


  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
      cache:
        cachecontrol:
          max-age: 365d
          cache-public: true

  devtools:
    restart:
      enabled: false

logging:
  level:
    root: ${LOGGING_ROOT_LEVEL:warn}
    dev.kirin.common.template: info
    dev.kirin: ${LOGGING_APP_LEVEL:info}

springdoc:
  swagger-ui:
    path: /docs/api/ui
    enabled: ${ENABLE_API_DOCS:false}
    csrf:
      enabled: true
      header-name: X-CSRF-TOKEN
      cookie-name: XSRF-TOKEN

  api-docs:
    path: /docs/api
    groups:
      enabled: true
    enabled: ${ENABLE_API_DOCS:false}

  default-produces-media-type: application/json
  group-configs:
    - group: default
      paths-to-match: /api/v1/**
  show-actuator: true
  writer-with-default-pretty-printer: true

app:
  encrypt:
    key-file: ${ENCRYPT_KEY_FILE:"classpath:default.key"}
  locale:
    parameter-name: lang
  plugins:
    mock-server:
      port: ${MOCK_SERVER_PORT:8081}